#!/bin/sh

# Set project-specific tmux session name
TMUX_SESSION="vsc-$(basename "$PWD")"
export TMUX_SESSION
echo "export TMUX_SESSION=\"vsc-$(basename "$PWD")\"" >>"$HOME/.zshrc.local"

# Since we mounted the SSH context in the Dockerfile as root, we need to change ownership
sudo chown -R "$USER":"$USER" "$HOME/.ssh"

# Create SSH config which includes the context-specific SSH config
cat >"$HOME/.ssh/config" <<EOF
# ===== AUTOGENERATED =====
Include $HOME/.ssh/contexts/$SSH_CONTEXT/config
Host *
  IdentitiesOnly yes
  ServerAliveInterval 60
EOF

# Setup container dotfiles
echo "Setting up dotfiles..."
CHEZMOI_DOTFILES_REPOSITORY="git@github.com:/${GITHUB_USERNAME}/devcontainer-dotfiles"
chezmoi init --apply "${CHEZMOI_DOTFILES_REPOSITORY}"

### FIXME: We're first copying the .zshrc file to the home directory via chezmoi,
## but now we're backing it up and linking it to a mounted location.
#
# Enable the mounted zsh configuration which was mounted under $HOME/.config/zsh
if [ -f "$HOME/.zshrc" ]; then
	mv "$HOME"/.zshrc "$HOME"/.zshrc.bak
fi
ln -sf "$HOME"/.config/zsh/.zshrc "$HOME"/.zshrc
