#!/bin/sh
# Universal post-create script for devcontainer environments
set -e

WORKSPACE_ROOT="${WORKSPACE_ROOT:-$PWD}"
SSH_CONTEXT="${SSH_CONTEXT:-default}"
AGENT_SOURCE_DIR="${WORKSPACE_ROOT}/docs/ai-dev-rules/agents"
AGENT_TARGETS="${WORKSPACE_ROOT}/.github/agents ${WORKSPACE_ROOT}/.amazonq/agents"

# ─── SSH ─────────────────────────────────────────────────────────────────────
echo "Setting up SSH configuration..."
if [ -d "$HOME/.ssh" ]; then
  sudo chown -R "$USER":"$USER" "$HOME/.ssh"
fi
mkdir -p "$HOME/.ssh"
cat >"$HOME/.ssh/config" <<EOF
# ===== AUTOGENERATED =====
Include $HOME/.ssh/contexts/$SSH_CONTEXT/config
Host *
  IdentitiesOnly yes
  ServerAliveInterval 60
EOF
echo "✓ SSH configuration complete"

# ─── ZSH ─────────────────────────────────────────────────────────────────────
echo "Setting up ZSH configuration..."
[ -f "$HOME/.zshrc" ] && mv "$HOME/.zshrc" "$HOME/.zshrc.bak" && echo "✓ Backed up existing .zshrc"
if [ -d "$HOME/.config/zsh" ] && [ -f "$HOME/.config/zsh/.zshrc" ]; then
  ln -sf "$HOME/.config/zsh/.zshrc" "$HOME/.zshrc"
  echo "✓ Linked ZSH configuration from $HOME/.config/zsh"
else
  echo "Info: No ZSH config mounted, skipping symlink"
fi

# ─── tmux ─────────────────────────────────────────────────────────────────────
echo "Setting up tmux configuration..."
if [ -f "$HOME/.tmux/tmux.conf" ]; then
  ln -sf "$HOME/.tmux/tmux.conf" "$HOME/.tmux.conf"
  echo "✓ Linked tmux configuration from $HOME/.tmux/tmux.conf"
else
  echo "Info: No tmux config found at $HOME/.tmux/tmux.conf, skipping"
fi

# ─── AI Agent Templates ───────────────────────────────────────────────────────
echo "Setting up AI agent templates..."
if [ ! -d "$AGENT_SOURCE_DIR" ]; then
  echo "Info: No ai-dev-rules/agents directory found, skipping"
else
  agent_count=$(find "$AGENT_SOURCE_DIR" -maxdepth 1 -name "*.agent.md" -type f 2>/dev/null | wc -l | tr -d ' ')
  if [ "$agent_count" -eq 0 ]; then
    echo "Info: No .agent.md files found, skipping"
  else
    for target_dir in $AGENT_TARGETS; do
      mkdir -p "$target_dir"
      for agent_file in "$AGENT_SOURCE_DIR"/*.agent.md; do
        [ -f "$agent_file" ] || continue
        agent_name=$(basename "$agent_file")
        [ -e "$target_dir/$agent_name" ] && rm -f "$target_dir/$agent_name"
        ln -sf "$agent_file" "$target_dir/$agent_name"
      done
      echo "✓ Symlinked agents to $(basename "$target_dir")"
    done
  fi
fi

# ─── Project-specific hook ────────────────────────────────────────────────────
PROJECT_POST_CREATE="${WORKSPACE_ROOT}/.devcontainer/post_create_project.sh"
if [ -f "$PROJECT_POST_CREATE" ]; then
  echo "Running project-specific post-create script..."
  chmod +x "$PROJECT_POST_CREATE"
  "$PROJECT_POST_CREATE"
fi

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo "========================================="
echo "✓ Devcontainer setup complete!"
echo "========================================="
echo "  Workspace: $WORKSPACE_ROOT"
echo "  User: $USER"
echo "  SSH Context: $SSH_CONTEXT"
echo ""
